def get_version() -> str:
    """Get version from hatch-vcs generated _version.py.

    In dev: generated by `uv sync` from git tags.
    In binary/Docker: generated at build time via SETUPTOOLS_SCM_PRETEND_VERSION.
    """
    try:
        from timba._version import __version__
        return __version__
    except ImportError:
        return "dev"
